export const instructors: InstructorProps[] = [
	{
		id: 1,
		name: "Dr. Sarah Johnson",
		avatar: "https://i.pravatar.cc/150?img=1",
		initials: "SJ",
		role: "Web Development Expert",
		students: 35420,
		courses: 12,
		rating: 4.9,
		specialties: ["JavaScript", "React", "Node.js"],
		isFeatured: true,
	},
	{
		id: 2,
		name: "David Chen",
		avatar: "https://i.pravatar.cc/150?img=8",
		initials: "DC",
		role: "AI & Machine Learning Specialist",
		students: 18240,
		courses: 8,
		rating: 4.8,
		specialties: ["Python", "TensorFlow", "Deep Learning"],
	},
	{
		id: 3,
		name: "Emily Parker",
		avatar: "https://i.pravatar.cc/150?img=5",
		initials: "EP",
		role: "Digital Marketing Strategist",
		students: 24680,
		courses: 10,
		rating: 4.7,
		specialties: ["SEO", "Social Media", "Content Marketing"],
		isFeatured: true,
	},
	{
		id: 4,
		name: "Alex Morgan",
		avatar: "https://i.pravatar.cc/150?img=3",
		initials: "AM",
		role: "UX/UI Designer",
		students: 21350,
		courses: 7,
		rating: 4.8,
		specialties: ["Figma", "User Research", "UI Design"],
	},
];
